-- 코드를 작성해주세요

SELECT YEAR(sub.YM) as YEAR, ROUND(AVG(sub.PM_VAL1), 2) as `PM10`, ROUND(AVG(sub.PM_VAL2), 2) as `PM2.5`
FROM (SELECT *
      FROM AIR_POLLUTION
      WHERE LOCATION2 = '수원') as sub
GROUP BY YEAR(sub.YM)
ORDER BY YEAR