-- 코드를 입력하세요
# 평균 대여 기간이 7일 이상인 자동차: DATEDIFF(END_DATE, START_DATE)

SELECT 
  c.CAR_ID, 
  ROUND(AVG(DATEDIFF(c.END_DATE, c.START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
GROUP BY c.CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, c.CAR_ID DESC;