-- 코드를 입력하세요

# 2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원수
## 
# 년, 월별로 출력

# 2021년에 가입한 전체 회원
WITH joined_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)

SELECT 
    YEAR(SALES_DATE), 
    MONTH(SALES_DATE), 
    COUNT(DISTINCT USER_ID) PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(*) FROM joined_2021), 1) PURCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID in (SELECT * FROM joined_2021)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
