-- 코드를 입력하세요

# 생산일자(PRODUCE_DATE)가 2022-05인 식품들
# 식품 ID, 식품 이름, 총매출 SUM((AMOUNT * PRICE))

SELECT fp.PRODUCT_ID, fp.PRODUCT_NAME, SUM(fo.AMOUNT * fp.PRICE) TOTAL_SALES
FROM FOOD_ORDER fo JOIN FOOD_PRODUCT fp ON fo.PRODUCT_ID = fp.PRODUCT_ID
WHERE fo.PRODUCE_DATE like '2022-05%'
GROUP BY MONTH(fo.PRODUCE_DATE), fo.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, fp.PRODUCT_ID
