-- 코드를 작성해주세요

SELECT s.ID, s.GENOTYPE, P.GENOTYPE as PARENT_GENOTYPE
FROM ECOLI_DATA s 
    LEFT JOIN ECOLI_DATA p ON s.PARENT_ID = p.ID
WHERE (s.GENOTYPE & p.GENOTYPE) = p.GENOTYPE
ORDER BY s.ID
    