-- 코드를 입력하세요

WITH valid_cars AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)

SELECT MONTH(START_DATE) as MONTH, CAR_ID, COUNT(*) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    AND CAR_ID in (SELECT CAR_ID FROM valid_cars)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE), CAR_ID DESC




# SELECT MONTH(sub.START_DATE) as MONTH, sub.CAR_ID, COUNT(sub.CAR_ID) as RECORDS
# FROM (
#     SELECT CAR_ID, START_DATE
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
# ) sub
# GROUP BY sub.CAR_ID, MONTH(sub.START_DATE)
# HAVING COUNT(sub.CAR_ID) >= 5
# ORDER BY MONTH(sub.START_DATE), sub.CAR_ID DESC