-- 코드를 작성해주세요
-- 이중 조인

SELECT fi.ID, fni.FISH_NAME, fi.LENGTH
FROM FISH_INFO fi
    LEFT JOIN (SELECT FISH_TYPE, MAX(LENGTH) as LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE) sub
    ON fi.FISH_TYPE = sub.FISH_TYPE
    AND fi.LENGTH = sub.LENGTH
LEFT JOIN FISH_NAME_INFO fni ON fi.FISH_TYPE = fni.FISH_TYPE
WHERE sub.LENGTH IS NOT NULL
ORDER BY fi.ID