-- 코드를 입력하세요

# 2022-01
# 카테고리별 GROUP BY CATEGORY
# 도서 판매량 합산 -> BOOK_SALES join BOOK on BOOK_ID
# 카테고리, 총 판매량 출력 -> CATEGORY, SUM(SALES)
# 카테고리명 오름차순

SELECT CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK_SALES bs JOIN BOOK b on bs.BOOK_ID = b.BOOK_ID
WHERE bs.SALES_DATE LIKE '2022-01%'
GROUP BY CATEGORY
ORDER BY CATEGORY