-- 코드를 입력하세요
# 1. 서브쿼리로 카테고리별 MAX PRICE를 먼저 구해준다
# 2. MAX_PRICE, CATEGORY를 기준으로 JOIN
# 3. ORDER BY

WITH sub as (
    SELECT CATEGORY, MAX(PRICE) MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY in ('과자','국','김치','식용유')
    GROUP BY CATEGORY
)

SELECT fp.CATEGORY, fp.PRICE MAX_PRICE, fp.PRODUCT_NAME
FROM FOOD_PRODUCT fp JOIN sub ON fp.CATEGORY = sub.CATEGORY 
    AND fp.PRICE = sub.MAX_PRICE
ORDER BY sub.MAX_PRICE DESC;